USE [master]
GO
/****** Object:  Database [gmDatabase]    Script Date: 10/16/2022 2:29:08 PM ******/
CREATE DATABASE [gmDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gmDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\gmDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'gmDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\gmDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [gmDatabase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gmDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [gmDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [gmDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [gmDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [gmDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [gmDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [gmDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [gmDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [gmDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [gmDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [gmDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [gmDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [gmDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [gmDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [gmDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [gmDatabase] SET  ENABLE_BROKER 
GO
ALTER DATABASE [gmDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [gmDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [gmDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [gmDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [gmDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [gmDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [gmDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [gmDatabase] SET RECOVERY FULL 
GO
ALTER DATABASE [gmDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [gmDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [gmDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [gmDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [gmDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [gmDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [gmDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'gmDatabase', N'ON'
GO
ALTER DATABASE [gmDatabase] SET QUERY_STORE = OFF
GO
USE [gmDatabase]
GO
/****** Object:  Table [dbo].[OrderDetail]    Script Date: 10/16/2022 2:29:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetail](
	[DetailID] [int] NOT NULL,
	[OrderID] [int] NOT NULL,
	[SeminarID] [int] NOT NULL,
 CONSTRAINT [PK_OrderDetail] PRIMARY KEY CLUSTERED 
(
	[DetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 10/16/2022 2:29:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderID] [int] NOT NULL,
	[OrderDate] [date] NOT NULL,
	[UserID] [int] NOT NULL,
	[TotalCost] [money] NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Payment]    Script Date: 10/16/2022 2:29:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Payment](
	[PaymentID] [int] NOT NULL,
	[OrderID] [int] NOT NULL,
	[PayID] [int] NOT NULL,
	[PayStatus] [varchar](25) NOT NULL,
 CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED 
(
	[PaymentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PayMethods]    Script Date: 10/16/2022 2:29:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PayMethods](
	[PayID] [int] NOT NULL,
	[Method] [varchar](25) NOT NULL,
 CONSTRAINT [PK_PayMethods] PRIMARY KEY CLUSTERED 
(
	[PayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reserved]    Script Date: 10/16/2022 2:29:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reserved](
	[SeminarID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[Reserved] [varchar](5) NOT NULL,
 CONSTRAINT [PK_Reserved] PRIMARY KEY CLUSTERED 
(
	[SeminarID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Seminars]    Script Date: 10/16/2022 2:29:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Seminars](
	[SeminarID] [int] NOT NULL,
	[SemName] [varchar](100) NOT NULL,
	[Added] [date] NOT NULL,
	[ContestWinner] [varchar](5) NULL,
	[Cost] [money] NOT NULL,
 CONSTRAINT [PK_Seminars] PRIMARY KEY CLUSTERED 
(
	[SeminarID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 10/16/2022 2:29:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] NOT NULL,
	[TFA] [varchar](5) NULL,
	[Username] [varchar](50) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[JoinDate] [date] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [idx_Orders]    Script Date: 10/16/2022 2:29:08 PM ******/
CREATE NONCLUSTERED INDEX [idx_Orders] ON [dbo].[OrderDetail]
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_Seminar]    Script Date: 10/16/2022 2:29:08 PM ******/
CREATE NONCLUSTERED INDEX [idx_Seminar] ON [dbo].[OrderDetail]
(
	[SeminarID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_OUser]    Script Date: 10/16/2022 2:29:08 PM ******/
CREATE NONCLUSTERED INDEX [idx_OUser] ON [dbo].[Orders]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_Payments]    Script Date: 10/16/2022 2:29:08 PM ******/
CREATE NONCLUSTERED INDEX [idx_Payments] ON [dbo].[Payment]
(
	[PayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_POrders]    Script Date: 10/16/2022 2:29:08 PM ******/
CREATE NONCLUSTERED INDEX [idx_POrders] ON [dbo].[Payment]
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_RUser]    Script Date: 10/16/2022 2:29:08 PM ******/
CREATE NONCLUSTERED INDEX [idx_RUser] ON [dbo].[Reserved]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderID] FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([OrderID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderID]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_SeminarID] FOREIGN KEY([SeminarID])
REFERENCES [dbo].[Seminars] ([SeminarID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_SeminarID]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_UserIDOrder] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_UserIDOrder]
GO
ALTER TABLE [dbo].[Payment]  WITH CHECK ADD  CONSTRAINT [FK_OrderIDPayment] FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([OrderID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Payment] CHECK CONSTRAINT [FK_OrderIDPayment]
GO
ALTER TABLE [dbo].[Payment]  WITH CHECK ADD  CONSTRAINT [FK_PayIDPayment] FOREIGN KEY([PayID])
REFERENCES [dbo].[PayMethods] ([PayID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Payment] CHECK CONSTRAINT [FK_PayIDPayment]
GO
ALTER TABLE [dbo].[Reserved]  WITH CHECK ADD  CONSTRAINT [FK_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Reserved] CHECK CONSTRAINT [FK_UserID]
GO
USE [master]
GO
ALTER DATABASE [gmDatabase] SET  READ_WRITE 
GO
