USE gmDatabase;
GO
ALTER TABLE Reserved WITH CHECK
ADD CONSTRAINT FK_UserID FOREIGN KEY(UserID) REFERENCES Users(UserID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_UserIDOrder
FOREIGN KEY(UserID) REFERENCES Users(UserID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetail WITH CHECK
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID) REFERENCES Orders(OrderID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetail WITH CHECK
ADD CONSTRAINT FK_SeminarID FOREIGN KEY(SeminarID) REFERENCES Seminars(SeminarID)
ON UPDATE CASCADE
GO
ALTER TABLE Payment WITH CHECK
ADD CONSTRAINT FK_OrderIDPayment FOREIGN KEY(OrderID) REFERENCES Orders(OrderID)
ON UPDATE CASCADE
GO
ALTER TABLE Payment WITH CHECK ADD CONSTRAINT FK_PayIDPayment
FOREIGN KEY(PayID) REFERENCES PayMethods(PayID) 
ON UPDATE CASCADE
GO